FROM ubuntu:22.04

RUN apt-get update
RUN apt-get install -y \
	git \
	build-essential \
	autoconf \
	texinfo

RUN apt-get install -y multitime nginx

COPY nginx.conf /etc/nginx/sites-available/default

RUN apt-get install -y \
	linux-modules-extra-$(uname -r) \
	rdma-core \
	libibverbs1 \
	libibverbs-dev \
	librdmacm1 \
	librdmacm-dev \
	rdmacm-utils \
	ibverbs-utils

RUN apt-get install -y \
	bash \
	curl \
	strace \
	gcc \
	make \
	netcat \
	lsof \
	iproute2 \
	htop \
	traceroute

WORKDIR /

CMD ["/bin/sh" "-c" "sleep infinity"]
